title: Siyuan HE's Homepage
page-top-title: Siyuan HE
top-section-bg-text: Be what you wanna be
home-subtitle: Siyuan HE&ensp;|&ensp;何思源
copyright-text: '&copy; Siyuan HE 2023-2025. All Rights Reserved.'
